apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp-deployment
  namespace: mateapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todoapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: todoapp
    spec:
      containers:
      - name: todoapp
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        image: ikulyk404/todoapp:3.0.0
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: api/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: api/ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
